### ISSUE TITLE
Could not load type when using EasyAdminBundle

### ISSUE THREAD

**Issue by allfreelancers** [fre5h/DoctrineEnumBundle#102]
After register type as
```
types:
     UserRoleType: AF\Bundle\UserBundle\DBAL\Types\UserRoleType
```
I get exception:
Could not load type "UserRoleType" 

why?

**Comment by fre5h** [comment]
@allfreelancers Show how you added @ORM annotations to your entity. And also what version of Symfony do you use?

**Comment by allfreelancers** [comment]
Symfony version  3.3.5

    /**
     * @ORM\Column(name="role", type="UserRoleType", nullable=false)
     * @DoctrineAssert\Enum(entity="AF\Bundle\UserBundle\DBAL\Types\UserRoleType")
     */
    private $role;

**Comment by allfreelancers** [comment]
namespace AF\Bundle\UserBundle\DBAL\Types;

use Fresh\DoctrineEnumBundle\DBAL\Types\AbstractEnumType;

class UserRoleType extends AbstractEnumType
{
    const BOTH = 'both';
    const FREELANCER = 'freelancer';
    const EMPLOYER = 'employer';

    protected static $choices = [
        self::BOTH => 'Both',
        self::FREELANCER => 'Freelancer',
        self::EMPLOYER => 'Employer'
    ];
}

**Comment by fre5h** [comment]
Try to add next, but I'm not sure if it help

```
doctrine:
    dbal:
        mapping_types:
            enum: string # <- this one
```

**Comment by allfreelancers** [comment]
@fre5h thx have same one:
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
            enum: string

but it dont work

**Comment by fre5h** [comment]
OK. Looks like you have done these steps.
* Created ENUM class
* Registered it in doctrine types config
* Added ORM annotation with your custom type to your entity.

The only one thing is left. What just to clarify if your have registered the bundle in AppKernel?

**Comment by allfreelancers** [comment]
@fre5h You mean?
new Fresh\DoctrineEnumBundle\FreshDoctrineEnumBundle(),
I have same

**Comment by fre5h** [comment]
Yes. OK. Right now I don't have any ideas. I think something wrong happened with a new version of Symfony. Need to investigate it. It will be bit later

**Comment by allfreelancers** [comment]
@fre5h Thank you very much, I will wait

**Comment by javiereguiluz** [comment]
@allfreelancers it's hard to read the code you paste in your comments. Lucikly there's a simple solution for that. You just need to add some ``` like this:

    ``` <-- add this before the code
    YOUR CODE HERE...
    ``` <-- add this after the code

And to enable highlighting, use this:

    ```yaml
    YOUR YAML CODE HERE...
    ```

    ```php
    YOUR PHP CODE HERE...
    ```

Thanks!

**Comment by allfreelancers** [comment]
@javiereguiluz thank you alot, I wose edit my posts

**Comment by allfreelancers** [comment]
@fre5h can you help me?

**Comment by fre5h** [comment]
@allfreelancers I am creating an example right now. Please wait few minutes

**Comment by fre5h** [comment]
@allfreelancers Check my example. I created a new repository on BitBucket https://bitbucket.org/fre5h/example/commits/all

It is a symfony project based on a fresh Symfony version 3.3.6. I used your ENUM type to reproduce the bug, but it works for me well. Go through my commits and compare what you have missed.

Instructions how to check my example:

1) Clone my repository
2) Run `composer install`
3) Set up parameters for your database connection (I'm using MySQL 5.6)
4) Run console command `doctrine:database:create`
5) Run console command `doctrine:schema:update --force`
6) After that go to the created database, you will see there the `example` table with `role` field which uses your UserRoleType ENUM

**Comment by fre5h** [comment]
@allfreelancers Please give me feedback, when you have something new

**Comment by allfreelancers** [comment]
@fre5h sorry for waiting response, I make all and in DB have
role | enum('both', 'freelancer', 'employer')

But I have the same thing and I have 
Could not load type "ProjectStatusType"

**Comment by fre5h** [comment]
As I understood, my example works for you!?
Error can be if you directory path does not math the namespace of your class, so the class with namespace `AF\Bundle\ProjectBundle\DBAL\Types` cannot be found because file is placed in wrong directory path, not PSR-4

**Comment by allfreelancers** [comment]
How to fix this?

**Comment by fre5h** [comment]
Compare directory structure with your namespace. They should be same.

**Comment by allfreelancers** [comment]
@fre5h structure in project correct, but my type ProjectStatusType was not loaded

you can make structure same mine?

**Comment by fre5h** [comment]
Yes, I can, but I am sure it will work for me. I think the problem is hidden somewhere in your code and you cannot see it (me also, because I don't see all your code in one place). If you can share your code with me or only leave those classes which are related to the problem I will try to help you.

**Comment by allfreelancers** [comment]
@fre5h install easyadmin and create new
https://easyadminbundle.readthedocs.io/en/latest/getting-started/

You will have same error "Could not load type "UserRoleType"

**Comment by fre5h** [comment]
@allfreelancers I have added EasyAdmin bundle to my example project. So with this bundle I could reproduce your error. You have to told about using this bundle at the very beginning of the conversation :)

**Comment by allfreelancers** [comment]
I'm sorry, but do we add our TYPE and it should work everywhere?

**Comment by fre5h** [comment]
There is the EnumTypeGuesser in my bundle. It adds a magic to the form, that you custom types become known for Symfony Forms. So I think EasyAdmin bundle changes this behavior somehow. Need more itme to investigate it

**Comment by javiereguiluz** [comment]
@fre5h we have some "form configurators" defined here: https://github.com/javiereguiluz/EasyAdminBundle/tree/master/Form/Type/Configurator Maybe that's messing with your bundle somehow :(

**Comment by allfreelancers** [comment]
@fre5h I thought that we set the global TYPE as STRING or DATETIME

**Comment by allfreelancers** [comment]
@javiereguiluz can you add ENUM type support?

**Comment by fre5h** [comment]
@javiereguiluz At first sight, the problem is that EnumGuesser is not called when EasyAdmin hooks start to create a form.
Here https://github.com/fre5h/DoctrineEnumBundle/blob/master/Form/EnumTypeGuesser.php#L73 EnumGuesser gets the FQCN of the registered type and returns a TypeGuess of ChoiceType with additional parameters.
I think the same guessing should be somewhere in EasyAdmin bundle. Or maybe @javiereguiluz can give an advise how I can tweak his bundle

**Comment by fre5h** [comment]
@allfreelancers Here is a quick and dirty solution for you. As EasyAdmin cannot guess enum form types right now, you should set them manually. Here is how your config can look like.
```yaml
easy_admin:
    entities:
        Example:
            class: AppBundle\Entity\Example
            list:
                fields:
                    - 'id'
                    - { property: 'role', type: 'text' }
            form:
                fields:
                    - { property: 'role', type: 'choice', type_options: { choices: {'Freelancer':'freelancer', 'Employer':'employer', 'Both':'both' } }  }
```

I understand that it is too much manual work for each entity which uses enums. But right now it can help you to solve your problem and move on until I find a way how to integrate it into EasyAdminBundle. I took a look on those configurators, I have some idea how to tweak it, but right now don't have enough time. So will continue fixing this issue few days later.

P.S. I also updated my bitbucket example where this config works

**Comment by allfreelancers** [comment]
@fre5h Thank you very much for your help, you are very sympathetic person

I use this solution

**Comment by FlxPeters** [comment]
Hi,

is there a better fix for the problem? As you said, this is not solution due to much  manual work. 
Any idea how to fix this? 

Thanks

**Comment by fre5h** [comment]
In EasyAdminBundle v3
```php

    public function configureFilters(Filters $filters): Filters
    {
        return $filters
            ->add(ChoiceFilter::new('someProperty', 'SomeLabel')->setChoices(EnumType::getChoices()))
        ;
    }
```
