### ISSUE TITLE
ContainerAwareEventDispatcher Deprecated warning

### ISSUE THREAD

**Issue by Bukashk0zzz** [fre5h/DoctrineEnumBundle#104]
User Deprecated: The Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher class is deprecated since version 3.3 and will be removed in 4.0. Use EventDispatcher with closure factories instead.

<img width="1082" alt="screen shot 2017-09-22 at 09 06 17" src="https://user-images.githubusercontent.com/1908342/30731317-69e7fb28-9f75-11e7-9288-c2f2080c3d72.png">

**Comment by fre5h** [comment]
@Bukashk0zzz Do you still have this error? Try version `6.0.1`

**Comment by Bukashk0zzz** [comment]
@fre5h Thanks all now ok.
