### ISSUE TITLE
Make readable_enum silently ignore NULLs

### ISSUE THREAD

**Issue by aminin** [fre5h/DoctrineEnumBundle#108]
The following entity

```php
class User
{
    …

    /**
     * @var string
     *
     * @ORM\Column(name="gender", type="GenderType", nullable=true)
     * @DoctrineAssertEnum(entity="GenderType")
     */
    private $gender;

    …
}
```

enum

```php
class GenderType extends AbstractEnumType
{
    const MALE      = 'male';
    const FEMALE    = 'female';

    protected static $choices = [
        self::MALE      => 'Knabo',
        self::FEMALE    => 'Knabino',
    ];
}
```

and twig template

```
{{  user.gender | readable_enum('GenderType') }}
```

produce an exception

```
"Invalid value "" for ENUM type "GenderType"
```

whereas `NULL` looks like _valid nothing_ that shouldn't cause an exception.

**Comment by fre5h** [comment]
@aminin Hi! It is possible to use NULL values for ENUM columns. But one of best practice is to use for NULL values a special ENUM value and doesn't allow to use null values. So in your case it can be

```php
class GenderType extends AbstractEnumType
{
    const MALE      = 'male';
    const FEMALE    = 'female';
    const UNKNOWN = 'unknown';

    protected static $choices = [
        self::MALE      => 'Knabo',
        self::FEMALE    => 'Knabino',
        self::UNKNOWN => 'Your text',
    ];
}
```

Use by default UNKNOWN value and you won't get this error.

**Comment by aminin** [comment]
However, introducind a *separate string value* for _empty choice_ solves the problem, it doesn't look like a best practice.

Using `null` to indicate _empty value_ is more intuitive and makes more sense.

**Comment by fre5h** [comment]
New release is v5.1.1
