### ISSUE TITLE
Strict constraint check validation

### ISSUE THREAD

**Issue by BenoitDuffez** [fre5h/DoctrineEnumBundle#111]
I have the following deprecation warning when submitting a form:

    Setting the strict option of the Choice constraint to false is deprecated since version 3.2 and will be removed in 4.0.

Here's how the field is declared:

	/**
	 * @var TeamRoleType
	 *
	 * @ORM\Column(name="role", type="TeamRoleType", nullable=false)
	 * @DoctrineAssert\Enum(entity="AppBundle\DBAL\Types\TeamRoleType")
	 */
	private $role;

Here's the type declaration:

	namespace AppBundle\DBAL\Types;

	use Fresh\DoctrineEnumBundle\DBAL\Types\AbstractEnumType;

	final class TeamRoleType extends AbstractEnumType {
		const TEAM_LEADER = 'TEAM_LEADER';
		const TEAM_MEMBER = 'TEAM_MEMBER';
		const TEAM_CUSTOMER = 'TEAM_CUSTOMER';
		/**
		 * Need to change?
		 * => https://github.com/fre5h/DoctrineEnumBundle#hook-for-doctrine-migrations
		 */
		protected static $choices = [
			self::TEAM_LEADER => "Chef d'équipe",
			self::TEAM_MEMBER => "Technicien",
			self::TEAM_CUSTOMER => "Client",
		];
	}

Here's the form type:

	/**
	 * {@inheritdoc}
	 */
	public function buildForm(FormBuilderInterface $builder, array $options) {
		// ...
		$builder->add('role', ChoiceType::class, ['choices' => TeamRoleType::getChoices()]);
		// ...
	}

I don't see what's wrong and I get the deprecation warning.

It's not a problem per se, except for my tests: phpunit returns exit code 1 when a deprecation is present and hence on my CI server the tests appear as failed even if they all pass.

**Comment by BenoitDuffez** [comment]
Forcing strict to true dismisses the deprecation warning:

    // vendor/fresh/doctrine-enum-bundle/Validator/Constraints/Enum.php:44
    $this->strict=true;

I have no idea why it does this and whether this bundle should set this field to `true`. Sorry, I'm still new to Symfony so I'm not very helpful.

**Comment by fre5h** [comment]
@BenoitDuffez thank for report. I will investigate this issue and give you feedback

**Comment by BenoitDuffez** [comment]
Great. I've updated this bundle to 5.1.1, same; I'm using Symfony 3.3.10

**Comment by fre5h** [comment]
@BenoitDuffez Take a new version 5.1.2 and enjoy :)

**Comment by BenoitDuffez** [comment]
Thanks for the insanely fast support on a sunday ;)
