### ISSUE TITLE
Remove dependency on symfony/form

### ISSUE THREAD

**Issue by enumag** [fre5h/DoctrineEnumBundle#120]
The symfony/form dependency should be optional. I want to use this bundle in an API-only project so there is no reason to install symfony/form.

**Comment by fre5h** [comment]
Right. Thanks. I will make this dependency optional. But also need to edit the code, so the EnumTypeGuesser should be added as service only if Symfony Form component is installed.

**Comment by enumag** [comment]
Yeah, exactly.

**Comment by fre5h** [comment]
@enumag `5.3.0` and `6.1.0` released
