### ISSUE TITLE
Form validation fails when choices are integers

### ISSUE THREAD

**Issue by stefandoorn** [fre5h/DoctrineEnumBundle#129]
I have this Type:

```
<?php

namespace SliderBundle\DBAL\Types;

use Fresh\DoctrineEnumBundle\DBAL\Types\AbstractEnumType;

/**
 * Class SlidePositionType
 */
final class SlidePositionType extends AbstractEnumType
{
    /**
     *
     */
    const POS_LEFT = 1;

    /**
     *
     */
    const POS_MID_TOP = 2;

    /**
     *
     */
    const POS_MID_BOTTOM = 3;

    /**
     *
     */
    const POS_RIGHT = 4;

    /**
     * @var array
     */
    protected static $choices = [
        self::POS_LEFT => 'Left',
        self::POS_MID_TOP => 'Mid Top',
        self::POS_MID_BOTTOM => 'Mid Bottom',
        self::POS_RIGHT => 'Right',
    ];
}
```

Usage in the form:

```
            ->add('position', ChoiceType::class, [
                'choices' => SlidePositionType::getChoices(),
                'label' => 'slider.form.position',
            ])
```

When using validation on it:

```
        position:
            - Fresh\DoctrineEnumBundle\Validator\Constraints\Enum:
                entity: SliderBundle\DBAL\Types\SlidePositionType
                groups: [app_slide]
```

For some reason the initial save goes correctly, but when editing it gets a validation error (`Choice::NO_SUCH_CHOICE_ERROR` by the check on line 99 in `vendor/symfony/symfony/src/Symfony/Component/Validator/Constraints/ChoiceValidator.php`). 

The submitted `$value` there is `string(1) "2"`, while the $choices are `array(4) { [0]=> int(1) [1]=> int(2) [2]=> int(3) [3]=> int(4) }`. The checks fails because by default `strict` mode is enabled on the `ChoiceValidator`.

As a workaround I have disabled `strict` mode, but that triggers a Symfony deprecation:

```
            @trigger_error('Not setting the strict option of the Choice constraint to true is deprecated since Symfony 3.4 and will throw an exception in 4.0.', E_USER_DEPRECATED);
```

Packages:
```
fresh/doctrine-enum-bundle                       v5.2.0             Provides support of ENUM type for Doctrine2 in Symfony applications.
symfony/symfony                                  v3.4.6             The Symfony PHP framework
```

**Comment by stefandoorn** [comment]
Seems introduced by https://github.com/fre5h/DoctrineEnumBundle/pull/112.

**Comment by fre5h** [comment]
@stefandoorn What version of bundle do you use?

**Comment by stefandoorn** [comment]
5.2.0 with Symfony 3.4.4.

**Comment by stefandoorn** [comment]
Excuse me, Symfony 3.4.6.

**Comment by fre5h** [comment]
@stefandoorn Do you really need integer values in ENUMS? Would you like to try
```
const POS_LEFT = '1';
// instead of
const POS_LEFT = 1;
```

**Comment by stefandoorn** [comment]
I'll try and let you know! I basically don't need integers (as it doesn't make that much sense in ENUM), but didn't think about that when creating it.

**Comment by fre5h** [comment]
And if you do not need integeres then you can write next
```
    const POS_LEFT = 'left';
    const POS_MID_TOP = 'top';
    const POS_MID_BOTTOM = 'bottom';
    const POS_RIGHT = 'right';
```
I think it is more ENUM-style way

**Comment by stefandoorn** [comment]
Yep. Internally it makes sense in this situation to have numeric values in the database, but they are perfectly fine to be strings instead of integers. Will try that first, but I think it will work.

**Comment by stefandoorn** [comment]
Simply adjusting the integers to strings does not work, as arrays keys get casted to integer when they are numeric. I will go temporary for a less strict validation in (and go with the deprecation notice) and migrate to strings later. Thanks!
