### ISSUE TITLE
Fix now invalid autowiring of ManagerRegistry instead of RegistryInterface

### ISSUE THREAD

**Issue by trappar** [fre5h/DoctrineEnumBundle#130]
After upgrading to [doctrine/DoctrineBundle 1.9.0](https://github.com/doctrine/DoctrineBundle/releases/tag/1.9.0) I'm getting the error:

`Cannot autowire service "Fresh\DoctrineEnumBundle\Form\EnumTypeGuesser": argument "$registry" of method "__construct()" references interface "Doctrine\Common\Persistence\ManagerRegistry" but no such service exists. You should maybe alias this interface to the existing "doctrine" service.`

To fix: [EnumTypeGuesser](https://github.com/fre5h/DoctrineEnumBundle/blob/master/Form/EnumTypeGuesser.php) should type-hint `RegistryInterface` rather than `ManagerRegistry`.

For now I'll just manually alias that in my project, so no pressure :)

**Comment by fre5h** [comment]
@trappar Sorry, but 1.9 is too old version and is not supported anymore

**Comment by trappar** [comment]
Please reread the issue. This has nothing to do with 1.9 of this bundle ;)

**Comment by fre5h** [comment]
@trappar You are right. Sorry.
What version of DoctrineEnumBundle do you use? And also do you use doctrine/common library and what version?

**Comment by fre5h** [comment]
@trappar Please check the tag `v6.2.1`
