### ISSUE TITLE
Invalid value for ENUM

### ISSUE THREAD

**Issue by Daisuke-sama** [fre5h/DoctrineEnumBundle#145]
Hi,
My ENUM class basically is shaped in a next way:
```
interface MyIn { public const CONST_1 = 1; }
interface HerIn {public const CONST_2 = 2; }
class TheEnum extends AbstractEnumType implements MyIn, HerIn {
  protected static $choices = [ self CONST_1.... ];
}
```
And these works fine. But types which just extended - aren't when I try to load fixtures - I constantly receive (not for all) but for specific (and every time unexpectedly selected) value the error with always different data for the same field:

> Invalid value "blob" for ENUM "VehicleColorType".
> Invalid value "dateinterval" for ENUM "VehicleColorType".
> Invalid value "date" for ENUM "VehicleColorType".
etc.

Why every time can the value so differ?

**Comment by fre5h** [comment]
@Daisuke-sama Hi. Sorry, but too less details. You wrote that you load fixtures, maybe problem is there, in the way how you load fixtures. Because I don't imagine how custom doctrine type can affect fixture loading. Need more details. Full code for your VehicleColorType and your fixture loader

**Comment by Daisuke-sama** [comment]
yes, sure, the code is below
```
class VehicleColorType extends AbstractEnumType
{
    public const OTHER = 0;
    public const WHITE = 1;
    public const MAROON = 2;

    protected static $choices = [
        self::OTHER  => [
            'name' => 'Другой',
            'code' => '',
        ],
        self::WHITE  => [
            'name' => 'Белый',
            'code' => '#FFFFFF',
        ],
        self::MAROON => [
            'name' => 'Бордовый',
            'code' => '#800000',
        ],
    ];
}
```
and a part of code from the fixture
```
protected function loadData() {
// ... some code
  $car = new Car();
  $car->setColor($this->getRandomValueOfClassConst(VehicleColorType::class));
// ... some code
}

protected function getRandomValueOfClassConst(string $theType)   {
    $reflection         = new \ReflectionClass($theType);
    $constVals          = array_values($reflection->getConstants());
    $randomSerialNumber = random_int(0, count($constVals) - 1);

     return $constVals[$randomSerialNumber];
}
```

**Comment by fre5h** [comment]
Hi. I've investigated your case. It works as it should work. You have public constants in your `VehicleColorType`. But also your class extends `AbstractEnumType`, which extends `Doctrine\DBAL\Types\Type`. Class `Type` has its own public constants, they are also available in your `VehicleColorType` as inherited. So it is not a surprise that you get them randomly in your script.

All this public constants can be returned by your random generator https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Types/Type.php#L19

So you have to implement different way to get random values from your `VehicleColorType`

**Comment by fre5h** [comment]
@Daisuke-sama  I've added a new method `getRandomValue` it is available in `v.6.3.0`. It might be useful for you

**Comment by fre5h** [comment]
And one more example how your function can be rewritten

```php
    protected function getRandomValueOfClassConst(string $enumType)
    {
        $reflectionOfCurrentType = new \ReflectionClass($enumType);
        $reflectionOfBaseType = new \ReflectionClass(\Doctrine\DBAL\Types\Type::class);

        $constantsOfCurrentType = array_values($reflectionOfCurrentType->getConstants());
        $constantsOfBaseType = array_values($reflectionOfBaseType->getConstants());

        $uniqueConstantsOfCurrentType = \array_diff($constantsOfCurrentType, $constantsOfBaseType);
        $randomSerialNumber = random_int(0, count($uniqueConstantsOfCurrentType) - 1);

        return $uniqueConstantsOfCurrentType[$randomSerialNumber];
    }
```

**Comment by Daisuke-sama** [comment]
oh, yeah, you are completely right. My carelessness. Thank you very much. I will be more accurate hereinafter!
