### ISSUE TITLE
Doesn't work with twig 3.0

### ISSUE THREAD

**Issue by ls-philippe-gamache** [fre5h/DoctrineEnumBundle#159]
Can install if twig 3.0 is used. 

$ composer require fresh/doctrine-enum-bundle
Using version ^6.6 for fresh/doctrine-enum-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "^4.4"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install fresh/doctrine-enum-bundle v6.6.1
    - Conclusion: remove twig/twig v3.0.0
    - Installation request for fresh/doctrine-enum-bundle ^6.6 -> satisfiable by fresh/doctrine-enum-bundle[v6.6.0, v6.6.1].
    - Conclusion: don't install twig/twig v3.0.0
    - fresh/doctrine-enum-bundle v6.6.0 requires twig/twig ~2.11 -> satisfiable by twig/twig[v2.11.0, v2.11.1, v2.11.2, v2.11.3, v2.12.0, v2.12.1, v2.12.2].
    - Can only install one of: twig/twig[v2.11.3, v3.0.0].
    - Can only install one of: twig/twig[v2.12.0, v3.0.0].
    - Can only install one of: twig/twig[v2.12.1, v3.0.0].
    - Can only install one of: twig/twig[v2.12.2, v3.0.0].
    - Can only install one of: twig/twig[v2.11.0, v3.0.0].
    - Can only install one of: twig/twig[v2.11.1, v3.0.0].
    - Can only install one of: twig/twig[v2.11.2, v3.0.0].
    - Installation request for twig/twig (locked at v3.0.0) -> satisfiable by twig/twig[v3.0.0].

**Comment by fre5h** [comment]
@ls-philippe-gamache Fixed. Please check the `v6.6.2`
