### ISSUE TITLE
It's possible to add support for PostgreSQL ENUM types?

### ISSUE THREAD

**Issue by reypm** [fre5h/DoctrineEnumBundle#17]
Even if bundle docs said it's only for MySQL I'm need to ask, it's possible to use in PostgreSQL? It's possible to use in schemas? Any chance to get this for PostgreSQL?

**Comment by mirzap** [comment]
what about alternative method, using check constraint?

https://wiki.postgresql.org/wiki/Enum

In laravel is implemented in similar way:

https://github.com/laravel/framework/blob/5.0/src/Illuminate/Database/Schema/Grammars/PostgresGrammar.php#L385

**Comment by fre5h** [comment]
@mirzap Thanks, I will implement it soon
