### ISSUE TITLE
Hook for doctrine migration as command

### ISSUE THREAD

**Issue by koninka** [fre5h/DoctrineEnumBundle#176]
As described in https://github.com/fre5h/DoctrineEnumBundle/blob/master/Resources/docs/hook_for_doctrine_migrations.md
we can update enum column by deleting comment. But I think it's complicated for developers always accessing DB and delete comments. 

What do you think about console command for deleting comments for specific enum such as `fresh:doctrine-enum:drop-comment SourceType`, where SourceType is argument for command?

**Comment by fre5h** [comment]
Good idea! I will consider it

**Comment by fre5h** [comment]
@koninka Done in `v7.3.0`
docs https://github.com/fre5h/DoctrineEnumBundle/blob/main/Resources/docs/hook_for_doctrine_migrations.md#console-command-for-dropping-comments
