### ISSUE TITLE
How can I translate the choices?

### ISSUE THREAD

**Issue by nkl90** [fre5h/DoctrineEnumBundle#177]
Hello. We use your bundle extensively in our project. But we had the task of translating the choices labels. We cannot inject the `TranslatorInterface` because the parent constructor in `Doctrine\DBAL\Types\Type` is final.

How can I do this as correctly as possible?

**Comment by fre5h** [comment]
Where do you need translations? In forms? Or in json response in case of RESTful API?

**Comment by fre5h** [comment]
@nkl90 ping

**Comment by nkl90** [comment]
We need translate choices in Form, Entities and in Twig templates. For example we have something Entity with enum param of ratign type:
```php
<?php

namespace App\DBAL\Types;

use Fresh\DoctrineEnumBundle\DBAL\Types\AbstractEnumType;

class RatingType extends AbstractEnumType
{
    const GLOBALY = 1;
    const MONTHLY = 2;
    protected static $choices = [
        self::GLOBALY => 'Глобальный',
        self::MONTHLY => 'Ежемесячный',
    ];
}
```
And in entty we create method:

```php
public function getRatingTypeName()
{
    return App\DBAL\Types\RatingType::getChoices()[$this->getRatingType()];
}
```
When we rendering this entity in twig, we do this:
```twig
<span>{{ ratingEntity.ratingTypeName }}</span>
```

In form we dot this:
```php
$builder
    ->add('description', TextareaType::class, [
        'choices' => App\DBAL\Types\RatingType::getChoices(),
    ]);
```

**Comment by fre5h** [comment]
OK. You can do this in the next way. I also do like this always

For example, this is your ENUM class

```php
<?php
namespace App\DBAL\Types;

use Fresh\DoctrineEnumBundle\DBAL\Types\AbstractEnumType;

final class HomeworkLevelEnumType extends AbstractEnumType
{
    public const LEVEL_ULTRA_LIGHT = 0;
    public const LEVEL_LIGHT = 1;
    public const LEVEL_PRO = 2;
    public const LEVEL_ULTRA_PRO = 3;
    public const LEVEL_TASK = 4;

    // create translation keys for you values
    public static $choices = [
        self::LEVEL_ULTRA_LIGHT => 'homework_level.ultra_light',
        self::LEVEL_LIGHT => 'homework_level.light',
        self::LEVEL_PRO => 'homework_level.pro',
        self::LEVEL_ULTRA_PRO => 'homework_level.ultra_pro',
        self::LEVEL_TASK => 'homework_level.task',
    ];
}
```

In your TWIG templates don't forget to add `|trans` filter. Because everything you want to be translated, should be processed by translator. And the ENUM class is not the place where translation should be done. ENUM is the responsibility of Model, and translations are the responsibility of View (Twig in this case)

```twig
<span>{{ ratingEntity.complexityLevelName|trans }}</span>
```
The only one thing left to do is to add translations for your choices.

```yaml
# messages.en.yaml
homework_level.ultra_light: Ultra Light
homework_level.light: Light
homework_level.pro: Pro
homework_level.ultra_pro: Ultra Pro
homework_level.task: Task
```

```yaml
# messages.ru.yaml
homework_level.ultra_light: Ультра
```

**Comment by fre5h** [comment]
@nkl90 Was it helpful?

**Comment by ADmad** [comment]
@fre5h Will following your suggestion translate the choices list returned by `HomeworkLevelEnumType::getChoices()`?

**Comment by fre5h** [comment]
@ADmad yes

**Comment by nkl90** [comment]
@fre5h yes! Thanks. That helped for me
