### ISSUE TITLE
Integer constants not fully supported?

### ISSUE THREAD

**Issue by colinodell** [fre5h/DoctrineEnumBundle#182]
Based on commit 98a34bb31bafb0cbb1068a9f7dffdbfe30762abf and [`NumericType.php`](https://github.com/fre5h/DoctrineEnumBundle/blob/master/Tests/Fixtures/DBAL/Types/NumericType.php) it seems like enums with integer constants/values should be supported.  However, several methods exist in `AbstractEnumType` which only accept `string` values, like `assertValidChoice()` and `getReadableValue()`.

Can you please confirm whether integers are indeed supposed to be supported and if this is a bug?

**Comment by fre5h** [comment]
Yes, integers are planned to be supported. So those methods, which accepts only `string` should be modified to accept `mixed`

**Comment by fre5h** [comment]
@colinodell In `v7.1.3` it is fixed
