### ISSUE TITLE
Compatibility issue between this and the `getsentry/sentry-symfony` bundle

### ISSUE THREAD

**Issue by ste93cry** [fre5h/DoctrineEnumBundle#187]
In getsentry/sentry-symfony#485, thanks to @adrienfr, we found out an incompatibility between this bundle and ours. We have two needs: the first one is to trace the performance of the DBAL for the [performance monitor](https://docs.sentry.io/product/performance/) feature provided by Sentry, and the second is that to log the errors we replace the Symfony error handler with our own. For the tracing feature to work, we decorate the connections using a custom class that wraps each method and tracks the time spent by each call. When your bundle boot, to register the custom Doctrine types you get the connection instances from the database

https://github.com/fre5h/DoctrineEnumBundle/blob/b2a1c524e629466f5770fa89eefc4f4e7039939b/FreshDoctrineEnumBundle.php#L45-L52

Since we're wrapping those connections, our SDK client gets initialized, which in turn executes the piece of code that replaces the error handler. When the `kernel.request` event is dispatched, the [`DebugHandlersListener::configure()`](https://github.com/symfony/symfony/blob/a9d582d681badfe20f3a4056a310d8abb9f57666/src/Symfony/Component/HttpKernel/EventListener/DebugHandlersListener.php#L74) method is called which does not find anymore the Symfony error handler and does not set the exception handler that calls `$kernel->terminateWithException()`. At that point, when an error occurs, our handler gets called, which calls the previous handler in the chain (the Symfony's one) which renders a default error page because no custom exception handler is configured anymore.

To me, the approach taken by this bundle is not the right one to register the custom Doctrine types. These kind of things are best done using a compiler pass: a good example of how you can do it can be found [here](https://github.com/symfony/symfony/blob/a9d582d681badfe20f3a4056a310d8abb9f57666/src/Symfony/Bridge/Doctrine/DependencyInjection/CompilerPass/RegisterUidTypePass.php).

**Comment by fre5h** [comment]
@ste93cry Thanks for explanation. I will take a look

**Comment by fre5h** [comment]
@ste93cry Release`7.2.0` is ready. In this release adding mapping types is rewritten via compiler pass

**Comment by ste93cry** [comment]
Thank you for such a quick fix. Hopefully, @adrienfr will solve his problem by updating 👍

**Comment by ste93cry** [comment]
Thank you for such a quick fix!
