### ISSUE TITLE
Support in phpstan-doctrine

### ISSUE THREAD

**Issue by AlexandruGG** [fre5h/DoctrineEnumBundle#195]
Hello!

I've been using this library for a little bit and I recently noticed that it doesn't have support in [phpstan-doctrine](https://github.com/phpstan/phpstan-doctrine). In other words, PHPStan doesn't know the types for the database and PHP values that are allowed on an entity that uses an enum property.

```PHP
final class InvoiceStatus extends AbstractEnumType
{
    public const PENDING = 'Pending';
    public const PAID = 'Paid';

    protected static $choices = [
        self::PENDING => 'Pending',
        self::PAID => 'Paid',
    ];
}


// usage in an entity omitted
// PHPStan error below:

Property App\Entity\AbstractInvoice::$status: Doctrine type "invoice_status" does not have any registered descriptor.
```

Thankfully, PHPStan is quite smart if type hints are used in `convertToDatabaseValue` and `convertToPHPValue`, and support for a new type can be added either in the phpstan-doctrine project itself ([here's](https://github.com/phpstan/phpstan-doctrine/pull/192) a recent one I did), or by the end-user in their own PHPStan configuration.

Would you be able to add return types for [these methods](https://github.com/fre5h/DoctrineEnumBundle/blob/main/DBAL/Types/AbstractEnumType.php#L45-L80)? I can prepare a PR as well, I just wanted to clarify: is an enum of mixed integers and strings allowed? I'm not quite sure what to make of the logic [here](https://github.com/fre5h/DoctrineEnumBundle/blob/main/DBAL/Types/AbstractEnumType.php#L72-L77), I've only been using this library for string enums.

**Comment by fre5h** [comment]
@AlexandruGG Can you create a drast PR, so we can discuss these return types in the code?
I didn't add support for mixed enums. Right now string and int values are supported. This one https://github.com/fre5h/DoctrineEnumBundle/blob/main/Tests/Fixtures/DBAL/Types/NumericType.php is used in tests.
