### ISSUE TITLE
Attempted to load class "DashboardAccountRoleType;" from namespace "App\DBAL\Types". Did you forget a "use" statement for another namespace?

### ISSUE THREAD

**Issue by xylipei** [fre5h/DoctrineEnumBundle#198]
Attempted to load class "DashboardAccountRoleType;" from namespace "App\DBAL\Types".
Did you forget a "use" statement for another namespace?

**Comment by fre5h** [comment]
Hi. I need to see your code, to find the reason

**Comment by xylipei** [comment]
> 你好。我需要看看你的代码，找出原因

doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'

        types:
            DashboardAccountRoleType: App\DBAL\Types\DashboardAccountRoleType;


namespace App\DBAL\Types;

use Fresh\DoctrineEnumBundle\DBAL\Types\AbstractEnumType;

final class DashboardAccountRoleType extends AbstractEnumType
{
    public const ROLE_EDITOR_TRAINEE = 'ROLE_EDITOR_TRAINEE';
    public const ROLE_EDITOR_PARTTIME = 'ROLE_EDITOR_PARTTIME';

    public const ROLE_EDITOR_JUNIOR = 'ROLE_EDITOR_JUNIOR';
    public const ROLE_EDITOR_MIDDLE = 'ROLE_EDITOR_MIDDLE';
    public const ROLE_EDITOR_SENIOR = 'ROLE_EDITOR_SENIOR';

    public const ROLE_EDITOR_DIRECTOR = 'ROLE_EDITOR_DIRECTOR';
    public const ROLE_EDITOR_MANAGER = 'ROLE_EDITOR_MANAGER';

    public const ROLE_BUSNESS = 'ROLE_BUSNESS';
    public const ROLE_MANAGER = 'ROLE_MANAGER';
    public const ROLE_FOUNDER = 'ROLE_FOUNDER';

    protected static $roles = [
        self::ROLE_EDITOR_TRAINEE => '....',
        ......
    ];
}

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Twig\Extra\TwigExtraBundle\TwigExtraBundle::class => ['all' => true],
    K911\Swoole\Bridge\Symfony\Bundle\SwooleBundle::class => ['all' => true],
    Fresh\DoctrineEnumBundle\FreshDoctrineEnumBundle::class => ['all' => true],
];


It's not quoted anywhere else

**Comment by fre5h** [comment]
Remove the `;`
```
        types:
            DashboardAccountRoleType: App\DBAL\Types\DashboardAccountRoleType;
```

```
        types:
            DashboardAccountRoleType: App\DBAL\Types\DashboardAccountRoleType
```

**Comment by xylipei** [comment]
thanks
