### ISSUE TITLE
add static methods

### ISSUE THREAD

**Issue by bigfoot90** [fre5h/DoctrineEnumBundle#20]
Some times I need to print a string rapresentation of the value in php.
So it would be helpful to have static methods like
```php
public static method asString($value)
```
And another method to check if a value is a valid choice
```php
public static method isValid($value)
```

Can I submit a **PR**?

**Comment by bigfoot90** [comment]
Sorry, I've realized now that methods ```getReadableValue``` and ```isValueExist```alredy exists.

**Comment by fre5h** [comment]
@bigfoot90 Yes, I think I will add this to README. Thanks
