### ISSUE TITLE
incorrect release 7.3.5

### ISSUE THREAD

**Issue by Gemorroj** [fre5h/DoctrineEnumBundle#205]
version 7.3.5 is identical to 7.3.4
see
https://github.com/fre5h/DoctrineEnumBundle/tree/v7.3.4
https://github.com/fre5h/DoctrineEnumBundle/tree/v7.3.5

the commit https://github.com/fre5h/DoctrineEnumBundle/commit/6278addf7907924f77d2ea9a7eb85269b07cd3b5 is not included to 7.3.5 release

**Comment by fre5h** [comment]
@Gemorroj thanks. 7.3.6 is ready
