### ISSUE TITLE
Psalm error `NonInvariantDocblockPropertyType`

### ISSUE THREAD

**Issue by ddebin** [fre5h/DoctrineEnumBundle#218]
Psalm made a design choice that class-level templates and static properties/method should not mix.
https://github.com/vimeo/psalm/issues/7507
https://psalm.dev/r/f5f3b15557

With current annotations in `AbstractEnumType`, Psalm throw an error
```
ERROR: NonInvariantDocblockPropertyType - [...] - Property A::$choices has type array<array-key, mixed>, not invariant with Fresh\DoctrineEnumBundle\DBAL\Types\AbstractEnumType::$choices of type array<Fresh\DoctrineEnumBundle\DBAL\Types\TValue, Fresh\DoctrineEnumBundle\DBAL\Types\TReadable>
```

With code
```php
/**
 * @extends AbstractEnumType<string,string>
 */
class A extends AbstractEnumType
{
    protected static array $choices = [ ];
}
```

**Comment by fre5h** [comment]
@ddebin Sorry, but this bundle doesn't use Psalm, it uses phpstan. I won't support both static analyzers. If you can create non-conflicted fix, I would consider it.
