### ISSUE TITLE
Where is changelog?

### ISSUE THREAD

**Issue by javaDeveloperKid** [fre5h/DoctrineEnumBundle#225]
I can't find any changelog file, any upgrade file. Release notes are very little. This package has 9 major versions so there must have been at least 9 BC breaks. How a user can know what's changed between major versions?

**Comment by fre5h** [comment]
@javaDeveloperKid Yes, you are right, it is missed. Because the main functionality wasn't changed since beginning. The only changes that were released in each major version were support of new major Symfony version.

**Comment by fre5h** [comment]
If you use version 8, you should see deprecations. In 9 version these deprecations are removed
https://github.com/fre5h/DoctrineEnumBundle/releases/tag/v9.0.0
Do you see any deprecation on running tests or in PhpStorm (if you use it)?
