### ISSUE TITLE
Could not load type

### ISSUE THREAD

**Issue by KonstantinKuklin** [fre5h/DoctrineEnumBundle#24]
Hi, I got the problem described in subject, I use symfony 2.6.4 with DoctrineEnumBundle.

My environment are:
```
Could not load type "MyType"
```

```
at FormRegistry ->getType ('MyType') 
in vendor/symfony/symfony/src/Symfony/Component/Form/FormFactory.php at line 82   + 
at FormFactory ->createNamedBuilder ('type', 'MyType', null, array()) 
in vendor/symfony/symfony/src/Symfony/Component/Form/FormBuilder.php at line 106   + 
at FormBuilder ->create ('type', 'MyType', array()) 
in vendor/symfony/symfony/src/Symfony/Component/Form/FormBuilder.php at line 268   + 
at FormBuilder ->resolveChildren () 
in vendor/symfony/symfony/src/Symfony/Component/Form/FormBuilder.php at line 216   + 
at FormBuilder ->getForm () 
in vendor/javiereguiluz/easyadmin-bundle/Controller/AdminController.php at line 395   + 
```

config.yml was configured:
```
doctrine:
    dbal:
        types:
            MyType: Some\MyBundle\Type\MyType
        mapping_types:
            enum: string
```
Entity which use MyType:
```
use Some\MyBundle\Type\MyType;
use Fresh\DoctrineEnumBundle\Validator\Constraints as DoctrineAssert;
use Doctrine\ORM\Mapping as Map;
*******
    /**
     * @DoctrineAssert\Enum(entity="Some\MyBundle\Type\MyType")
     * @Map\Column(name="type", type="MyType", nullable=false)
     */
    private $type;
```
MyType content:
```
class MyType extends AbstractEnumType
{

    const TEXT_ID = '1';
    const INTEGER_ID = '2';
    const NUMBER_ID = '3';
    const FILE_ID = '4';

    protected static $choices = array(
        self::TEXT_ID => 'text',
        self::INTEGER_ID => 'integer',
        self::NUMBER_ID => 'number',
        self::FILE_ID => 'file'
    );
}
```
Could you help me to understand what I do wrong?

**Comment by fre5h** [comment]
@KonstantinKuklin Did you add bundle in AppKernel?

**Comment by KonstantinKuklin** [comment]
@fre5h sure

**Comment by fre5h** [comment]
I see you got this error in `FormBuilder` can you share the code of your form?

**Comment by KonstantinKuklin** [comment]
I use EasyAdminBundle to generate admin pages, it generate forms in real time
I showed how it try to generate form the above

**Comment by fre5h** [comment]
It is not a problem of DoctrineEnumBundle, it is a problem of EasyAdminBundle. I guess it takes field type from annotations, as it is `MyType` it doesn't find such registered form type and fails.
As I described here https://github.com/fre5h/DoctrineEnumBundle#building-the-form You can not specify field type in form, then it will be guessed. Or you can set it as `choice`. Maybe there you can tweak it in EasyAdminBundle.

**Comment by KonstantinKuklin** [comment]
thank you very much, you were right!

**Comment by luispabon** [comment]
@KonstantinKuklin how did you go on about fixing this? Did you override Easy's admin controller? Or via config?

**Comment by KonstantinKuklin** [comment]
@luispabon oh man, it was so long ago, it seems, that I hacked easy admin a little, but code lost
