### ISSUE TITLE
Enums wont reload after updating

### ISSUE THREAD

**Issue by bsaverino** [fre5h/DoctrineEnumBundle#25]
I have run into an issue where I went back and needed to modify a few of the constant values and add a few more.  However I was getting an error after the changes occurred.  Error read `Uncaught PHP Exception Symfony\Component\Routing\Exception\RouteNotFoundException: "Unable to generate a URL for the named route "" as such route does not exist." at ..\appDevUrlGenerator.php line 134`  
I couldn't figure out what the issue was being that the enums were working without any issue at all prior to the change.  

I removed the doctrine relation for the field I was having issues with, forced the update then added it back  in and forced the update again.  The issue went away without any problem.  

Before:
```
<?php
namespace RLD\AppBundle\DBAL;

use Fresh\DoctrineEnumBundle\DBAL\Types\AbstractEnumType;

class AppStep extends AbstractEnumType
{
    const NONE = "Loan Information";  //HASN'T YET COMPLETED STEP ONE
    const ONE = "Primary Personal Info";  //COMPLETED STEP 1
    const TWO = "Co Personal Info";  //COMPLETED STEP 2
    const THREE = "Primary Employment";
    const FOUR = "Co Employment";
    const FIVE = "Income";
    const SIX = "Expense";
    const SEVEN = "Submit";
    const COMPLETE = "Completed";

    /**
     * @var array Readable choices
     * @static
     */
    protected static $choices = [
        self::NONE => 'no steps completed',
        self::ONE => 'Step 1 completed',
        self::TWO => 'Step 2 completed',
        self::THREE => 'Step 3 completed',
        self::FOUR => 'Step 4 completed',
        self::FIVE => 'Step 5 completed',
        self::SIX => 'Step 6 completed',
        self::SEVEN => 'Step 7 completed',
        self::COMPLETE => 'Application completed'
    ];
}
```

After:
```
<?php
namespace AppBundle\DBAL;

use Fresh\DoctrineEnumBundle\DBAL\Types\AbstractEnumType;

class AppStep extends AbstractEnumType
{
    const NONE = "Loan Information";  //HASN'T YET COMPLETED STEP ONE
    const ONE = "Primary Personal Info";  //COMPLETED STEP 1
    const TWO = "Co Personal Info";  //COMPLETED STEP 2
    const THREE = "Primary Employment";
    const FOUR = "Co Employment";
    const FIVE = "Income";
    const SIX = "Expense";
    const SEVEN = "Government Monitoring";
    const EIGHT = "Review Application";
    const NINE = "Submit";
    const COMPLETE = "Completed";

    /**
     * @var array Readable choices
     * @static
     */
    protected static $choices = [
        self::NONE => 'no steps completed',
        self::ONE => 'Step 1 completed',
        self::TWO => 'Step 2 completed',
        self::THREE => 'Step 3 completed',
        self::FOUR => 'Step 4 completed',
        self::FIVE => 'Step 5 completed',
        self::SIX => 'Step 6 completed',
        self::SEVEN => 'Step 7 completed',
        self::EIGHT => 'Step 8 completed',
        self::NINE => 'Step 9 completed',
        self::COMPLETE => 'Application completed'
    ];
}
```

**Comment by fre5h** [comment]
@bsaverino So you think this issue is related to this bundle? This issue happened in routing, so maybe problem is there. Anyway when you add new values to ENUM field you must update migration as it is described in the bottom of documentation. What is the pattern of the route which threw the exception.

**Comment by bsaverino** [comment]
Ah, I see.  Sorry it was not overly obvious to look in a section that I didn't think applied to me.  However that section does address the issue I was having.  I am not saying at all that it is the fault of your bundle just more or less making you aware of it incase you wanted to add a "Making Changes" section.  I found your bundle to be very useful and I appreciate your time.  I figure it doesn't hurt trying to make something better or help the next person that comes along.  

To answer your question about the route it looks like this 
```
    /**
    * @Route("/review/{app}", name="Review App")
    */
```

**Comment by fre5h** [comment]
OK. Looks like simple cache problem. I don't see any relations to ENUMs.

**Comment by bsaverino** [comment]
I wouldn't chalk it up to a caching issue.  I run `php app/console cache:clear`  pretty frequently as well as other precautions.  This problem also existed over the course of weeks but it was in a branch that wasn't being worked on at the time and was labeled as a bug.  I think that really helps clarify a non caching issue.

**Comment by fre5h** [comment]
If this issue is gone for you then OK. Until I can't reproduce it I can't realize the problem.
