### ISSUE TITLE
Schema update, postgres and enum

### ISSUE THREAD

**Issue by luispabon** [fre5h/DoctrineEnumBundle#33]
Currently, when doing a schema update and modifying a field from something to one of our enum types, the resulting sql is like:

```sql
ALTER TABLE table_name ALTER column_in_question TYPE VARCHAR(255) CHECK(column_in_question IN  table_name(  ('foo', 'bar', 'foobar'));
```

The correct syntax is:
```sql
ALTER TABLE table_name ADD CHECK(column_in_question IN  table_name(('foo', 'bar', 'foobar'));
```

Creating the schema from scratch works with the current syntax however.

Maybe you can refactor so that it a) creates the column with a string type and b) issues the correct alter table command?

**Comment by fre5h** [comment]
Doctrine creates SQL definitions field by field. So bundle is responsible only for the part ` CHECK(column_in_question IN  table_name(  ('foo', 'bar', 'foobar'))`. As far as I know it is impossible to move out of the scope of field and change other parts on SQL statement. I wish Doctrine would have a feature to make this possible (some event or cutomization) but right now it doesn't have. So updating the SQL statement for ENUM is manually job. Unfortunately :(

**Comment by luispabon** [comment]
Understood :+1: thank you very much.
