### ISSUE TITLE
Symfony 3 support

### ISSUE THREAD

**Issue by Bukashk0zzz** [fre5h/DoctrineEnumBundle#34]
Hi,

I try today update my project to symfony 3 beta release and only one package that still not support it are DoctrineEnumBundle

I think migrate to symfony 3 your package not a problem. There are no deprecation in it.
Also in doc "Symfony 2.5 and later" you need to change "Symfony 2.5 and later, but < Symfony 3.0".

If you planed migrate to new version please make new branch or make tag with old version. 
If you not planned to update I will made fork and update code for symfony 3. Thanks.

**Comment by fre5h** [comment]
Surely I plan to update bundle to Symfony 3.0. Right now I am using it with Symfony 2.8 beta and have no problems. As soon as stable Symfony 3.0 will be released I will update bundle and create new branch or tag. It should be till the end of this month.

**Comment by luispabon** [comment]
Symfony 3 was released yesterday :+1:

**Comment by fre5h** [comment]
I know that. Just don't have a free time right now. Need few days to complete it.

**Comment by luispabon** [comment]
Is there a lot to do? Perhaps I can help.

**Comment by fre5h** [comment]
I don't know exactly. I use this bundle with Symfony 2.8 and don't have any problem. In the fact that Symfony 2.8 has same API as Symfony 3.0 I don't really know what could broke.
Maybe it just needed to update symfony version in composer.json.

**Comment by luispabon** [comment]
I'm just trying this on my own fork, will report back :+1:

**Comment by luispabon** [comment]
Tests highlight a number of issues, just running through them

**Comment by fre5h** [comment]
If you fix it faster than me, then make PR into this branch
https://github.com/fre5h/DoctrineEnumBundle/tree/feature-symfony-3.0

**Comment by luispabon** [comment]
:+1:

**Comment by luispabon** [comment]
I'm down to the last test error

**Comment by fre5h** [comment]
Use `php composer.phar require fresh/doctrine-enum-bundle='v4.0'` for Symfony 3.0
