### ISSUE TITLE
Doctrine not recognising enum

### ISSUE THREAD

**Issue by jonathanbull** [fre5h/DoctrineEnumBundle#38]
Hi,

I've set up by enum in Symfony 3.0 using the instructions in the README, but when I run `bin/console doctrine:schema:update`, Doctrine just wants to drop my column:

    /*
     * @ORM\Column(name="status", type="StatusType")
     * @DoctrineAssert\Enum(entity="MyProject\MyBundle\DBAL\Types\StatusType")
     */
    private $status; 

    doctrine:
        dbal:
            driver:   pdo_mysql
            host:     "%database_host%"
            port:     "%database_port%"
            dbname:   "%database_name%"
            user:     "%database_user%"
            password: "%database_password%"
            charset:  UTF8
            mapping_types:
                enum: string
            types:
                StatusType:            MyProject\MyBundle\DBAL\Types\StatusType

    namespace MyProject\MyBundle\DBAL\Types;
    use Fresh\DoctrineEnumBundle\DBAL\Types\AbstractEnumType;

    final class StatusType extends AbstractEnumType
    {
        const DRAFT = 'DRAFT';
        const SENT = 'SENT';

        protected static $choices = [
            self::DRAFT => 'Draft',
            self::SENT => 'Sent',
        ];
    }

I've registered `Fresh\DoctrineEnumBundle\FreshDoctrineEnumBundle` in my AppKernel. Have I missed something?

**Comment by fre5h** [comment]
It happens only during update?

**Comment by jonathanbull** [comment]
Thanks for the prompt reply. It also happens on `doctrine:schema:create`.

**Comment by fre5h** [comment]
I'm not sure what is it. Maybe it is a bug, but I'm not sure. I don't work with Symfony 3.0 now, continue working with 2.8. If it is a bug, then it is not related to Symfony, I think it is more related to the Doctrine. But need to check.
I described the known issue related to migrations https://github.com/fre5h/DoctrineEnumBundle#hook-for-doctrine-migrations Maybe it is related somehow.
I will take a look on this issue some time later. If you have some new information about it, please add it here.
I know that few guys use this bundle with Symfony 3.0 and I didn't receive any issues from them.

**Comment by fre5h** [comment]
@jonathanbull 
Please check the comment type above your field, your example
```
/*
 * @ORM\Column(name="status", type="StatusType")
 * @DoctrineAssert\Enum(entity="MyProject\MyBundle\DBAL\Types\StatusType")
 */
private $status; 
```
But should be
```
/**
 * @ORM\Column(name="status", type="StatusType")
 * @DoctrineAssert\Enum(entity="MyProject\MyBundle\DBAL\Types\StatusType")
 */
private $status; 
```
Use `/**` instead of `/*`. Your annotations are not inside docblocks, that's why field is not visible by Doctrine.
Please give feedback if it helped you.

**Comment by jonathanbull** [comment]
You're a life saver! Can't believe I missed that, thank you very much.
