### ISSUE TITLE
Enum form choices backwards when using Symfony 3

### ISSUE THREAD

**Issue by jaimz22** [fre5h/DoctrineEnumBundle#40]
Prior to Symfony 3, there was the form choice option of "choices_as_values" which would use arrays as such:

```php
[
     'value'=>'label'
]
```
when using 'choices_as_values' => false which is how this the choices are handled for the enums. This means that in symfony 3, the enum value is shown as the label and the label is shown as the value.

Later they in symfony 3, they removed the 'choices_as_values' option from the choices form type and set the form type to be as if 'choices_as_values' is true. This means that in your enum choices array you need to make them as:

```php
[
     'label'=>'value'
]
```

Doing this displays the values and labels correctly, however upon submitting the form, you'll receive the error that "The value you selected is not a valid choice." This is because your choices array is now flipped from the way that the enums type checks for the valid value.

I was able to get around this by using array_flip() in my form builder ```array_flip(\Acme\Enum\MyEnum::getChoices())``` but I feel like this is something that should be addressed in the getChoices() method, or in the place that the submitted value is checked.

**Comment by jonathanbull** [comment]
Was also getting tripped up by this... thanks for the array_flip workaround, jaimz22!

**Comment by fre5h** [comment]
Guys, please check the version v4.2, it has fixed this issue.
