### ISSUE TITLE
Support of SET fields

### ISSUE THREAD

**Issue by ABM-Dan** [fre5h/DoctrineEnumBundle#41]
Would this be possible? Would it be easy?

**Comment by fre5h** [comment]
Check this https://github.com/fre5h/DoctrineEnumBundle/issues/8
If it be implemented then not in this bundle, but in separate, like DoctrineSetBundle.

**Comment by ABM-Dan** [comment]
Thank you for the prompt answer, what is funny is that I actually confused the two, I need enum and not set. And you're mostly right in that set is not the greatest pattern. That does propmpt me to ask another question.
