### ISSUE TITLE
Many Yaml parse error in Sf 2.8

### ISSUE THREAD

**Issue by jewome62** [fre5h/DoctrineEnumBundle#45]
Hello !

With the Yaml parser update for Symfony 2.8.
I have many deprecated with the @ in config.yml

You have fix it for the version 4.0
Can you apply the same correction on 3.3 ? (and create 3.3.1 ?)

https://github.com/fre5h/DoctrineEnumBundle/commit/0f2f27c9ac79dedc3a737fc94574d754a7040226#diff-a08c782a2ee112dc4ee0a0152ba6c6ccL24

Thanks a lot

**Comment by fre5h** [comment]
@jewome62 As I understood, you are using EnumBundle v3.3 with Symfony 2.8?

**Comment by jewome62** [comment]
Yes it is

Envoyé depuis mon iPhone

**Comment by fre5h** [comment]
@jewome62 So you can just use the version 4.1, it has all fixes of deprecations. I am currently use 4.1 in my projects with Symfony 2.8 and it works. Version 4.1 works well with Symfony 2.8 and also supports Symfony 3.0

**Comment by jewome62** [comment]
Ok, Thanks for information
Sorry for the noise

:beers:
