### ISSUE TITLE
Inverted choices in symfony 3

### ISSUE THREAD

**Issue by rafrsr** [fre5h/DoctrineEnumBundle#47]
All choices appear inverted value=>label when use with symfony 3.

from symfony documentation:

2.3
The choices option is an array, **where the array key is the item value and the array value is the item's label**

3.0

The choices option is an array, **where the array key is the item's label and the array value is the item's value**

**Comment by fre5h** [comment]
I'am planning to fix it on this weekend

**Comment by fre5h** [comment]
Please check the version v4.2, it has fixed this issue
