### ISSUE TITLE
Naming filter `readable` is confusing

### ISSUE THREAD

**Issue by sustmi** [fre5h/DoctrineEnumBundle#53]
I have first-person and second-person experience with your bundle and the filter name `readable` is quite confusing. I had no idea what is this filter supposed to do until I was told that it has something to do with enums.
I suggest renaming the filter to either:
`enum_readable` (so that there is a common prefix with `enum_constant`)
or:
`readable_enum` (it reads better).

We can choose a new name, change it in the documentation and keep the current `readable` filter but deprecate it (for backward compatibility and easier migration). (See http://twig.sensiolabs.org/doc/advanced.html#deprecated-filters .)

**Comment by fre5h** [comment]
I'll think about it. Thanks

**Comment by sustmi** [comment]
If we agree on the name I can implement it and send you a pull-request. ;)

**Comment by fre5h** [comment]
I prefer `readable_enum`. So if you implement it, it will be great! But don't forget to add/update all related tests ^_^

**Comment by sustmi** [comment]
Maybe I am over-thinking it, but I came with another name for the filter: `enum_label`.
I think it is the best of all mentioned.
First, it has the prefix `enum_` which I think is good since Twig filters have no concept of namespaces and in big applications there can be collisions or ambiguity.
Second, `readable` is good, but my opinion is that `label` describes it more precisely, because the returned string is the label of the choice.
What do you think @fre5h ?

**Comment by sustmi** [comment]
Oh, I can see that the term *readable* is scattered in lot of places in the code. :/
Ok, let's stick with `readable_enum` for the filter name as it is the closest we can get to the rest of the code (`AbstractEnumType::getReadableValue()` and `ReadableEnumValueExtension::getReadableEnumValue()`).

**Comment by fre5h** [comment]
Thanks
