### ISSUE TITLE
Create Schema

### ISSUE THREAD

**Issue by fussl** [fre5h/DoctrineEnumBundle#57]
Hello everybody,

i guess there is an issue with the schema creation.
I followed your tutorial, but i cant create my schema.
Pls help me :+1: 

> [Doctrine\DBAL\DBALException]
>   Unknown column type "enum" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType().
>   You can get a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap(). If this error occurs during database introsp
>   ection then you might have forgot to register all database types for a Doctrine Type. Use AbstractPlatform#registerDoctrineTypeMappin
>   g() or have your custom types implement Type#getMappedDatabaseTypes(). If the type name is empty you might have a problem with the ca
>   che or forgot some mapping information.

AppKernel:
`new Fresh\DoctrineEnumBundle\FreshDoctrineEnumBundle(),`

config.yml 
```
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        server_version: 5.6
        mapping_types:
            enum: string
        types:
            GameStatusType: AppBundle\DBAL\Types\GameStatusType
            GangStatusType: AppBundle\DBAL\Types\GangStatusType
            ChallengeStatusType: AppBundle\DBAL\Types\ChallengeStatusType
            ChallengeFinishRuleType: AppBundle\DBAL\Types\ChallengeFinishRuleType
            InformationStatusType: AppBundle\DBAL\Types\InformationStatusType
            MediaTypeType: AppBundle\DBAL\Types\MediaTypeType
```

example: ChallengeFinishRule
```
namespace AppBundle\DBAL\Types;

use Fresh\DoctrineEnumBundle\DBAL\Types\AbstractEnumType;

final class ChallengeFinishRuleType extends AbstractEnumType
{

    const TIME = 'TI';
    const ROUNDS = 'RO';

    protected static $choices = [
        self::TIME => 'challenge.rule.time',
        self::ROUNDS => 'challenge.rule.rounds',
    ];
}
```

Attribute in ChallengeClass
Challenge Class has "use AppBundle\DBAL\Types\ChallengeFinishRuleType";
```
    /**
     * @var string
     *
     * @ORM\Column(name="finish_rule", type="ChallengeFinishRuleType", nullable=false)
     * @DoctrineAssert\Enum(entity="AppBundle\DBAL\Types\ChallengeFinishRule")
     */
    private $finishRule;
```

Composer
```
 "symfony/symfony": "3.0.*",
        "doctrine/orm": "^2.5",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-cache-bundle": "^1.2",
        "symfony/swiftmailer-bundle": "^2.3",
        "symfony/monolog-bundle": "^2.8",
        "sensio/distribution-bundle": "^5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "^2.0",
        "friendsofsymfony/user-bundle": "~2.0@dev",
        "fresh/doctrine-enum-bundle": "4.5",
        "gedmo/doctrine-extensions": "^2.4"
```

**Comment by fre5h** [comment]
I inspected your code examples and did not see anything wrong there. But the error message `Unknown column type "enum" requested.` looks like you have an `enum` type somewhere. Maybe in some entity you have `@ORM\Column(type="enum", nullable=false)` annotation. I could reproduce your issue with this annotation. Reinvestigate your code.

**Comment by fre5h** [comment]
@fussl was it helpful?

**Comment by fussl** [comment]
yes
