### ISSUE TITLE
Updating Enum Types

### ISSUE THREAD

**Issue by pascalwacker** [fre5h/DoctrineEnumBundle#59]
When I run `php bin/console doctrine:schema:update --force` on a Symfony 3.1 installation (not tested in any other), it doesn't update the Enum field in the db, when I add a new Type.

I can either drop that table and recreate it with above command or add the new type manually. It would be nice, if the console command could take care of that (specially to have the dev and prod server in sync).

**Comment by fre5h** [comment]
Hi. It is not possible right now to fix it. Check this related issue https://github.com/fre5h/DoctrineEnumBundle/issues/33

I wrote in docs https://github.com/fre5h/DoctrineEnumBundle#hook-for-doctrine-migrations what to do if you want to update schema (just remove comment from the column definition)

**Comment by sfenne** [comment]
If you don't mind your `php bin/console doctrine:schema:update --force` always returning 
> Database schema updated successfully! "1" query was executed

You could do this trick to force enum to be updated every time (automatically).

In your entity, specify a constant as value for the columns comment section.
For example:

`* @ORM\Column(type="YourEnumType", nullable=true, options={"comment":AppBundle\DBAL\Types\YourEnumType::ONE_OF_YOUR_CONSTANTS})`
