### ISSUE TITLE
Bundle has complete symfony framework as dependency in composer.json

### ISSUE THREAD

**Issue by fadoe** [fre5h/DoctrineEnumBundle#61]
Your Bundle has the complete symfony framework as requirement. Can you only include the needed components in the composer.json, please?

**Comment by fre5h** [comment]
OK, I will check required dependencies in the evening and decide what can be omitted.

**Comment by fadoe** [comment]
Great. Thank you.

**Comment by fre5h** [comment]
Take this version v4.6.3
