### ISSUE TITLE
doc error

### ISSUE THREAD

**Issue by ktwbc** [fre5h/DoctrineEnumBundle#65]
in your directions on packagist, you have an example

Symfony >= 3.0
$builder->add('position', '\Symfony\Component\Form\Extension\Core\Type\ChoiceType', [
    'choices' => BasketballPositionType::getChoices()
]);

note should be:

$builder->add('position', ChoiceType::class, [

**Comment by fre5h** [comment]
@ktwbc Thank you. Nice catch!
