### ISSUE TITLE
Conflict with twig upgrade

### ISSUE THREAD

**Issue by RaphaelSalique** [fre5h/DoctrineEnumBundle#67]
I use Symfony 2.8 and your bundle for my project.

When I launched "composer update" this morning, the "cache:clear" step failed with this error : "PHP Fatal error:  Cannot make non abstract method Twig_Extension::getName() abstract in class Fresh\DoctrineEnumBundle\Twig\Extension\AbstractEnumExtension"

Twig has upgraded from 1.25 to 1.26 - it seems that Twig_ExtensionInterface::getName() is deprecated.

**Comment by fre5h** [comment]
@RaphaelSalique it is because recent changes in Twig 1.26. Patch is ready, waiting until tests pass

**Comment by RaphaelSalique** [comment]
Thanks a lot :-)

**Comment by fre5h** [comment]
New patched version 4.6.5

**Comment by jdecoster** [comment]
@fre5h can you bump this to the 4.7.x release ?
