### ISSUE TITLE
help me for this error

### ISSUE THREAD

**Issue by lotfikhalifa** [fre5h/DoctrineEnumBundle#86]
[Doctrine\Common\Annotations\AnnotationException] [semantical Error]couldn't find constant cascade, property oilexport\oilexportBundle\Entity\categories::$image

entity categories.php:
*********************
<?php

namespace Oilexport\OilexportBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * categories
 *
 * @ORM\Table("categories")
 * @ORM\Entity(repositoryClass="Oilexport\OilexportBundle\Repository\CategoriesRepository")
 */
class categories
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\OneToOne(targetEntity="Oilexport\OilexportBundle\Entity\Media", cascade("persist","remove"))
     * @ORM\JoinColumn(nullable=false)
     */
    private $image;

    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", length=125)
     */
    private $nom;

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set nom
     *
     * @param string $nom
     * @return categories
     */
    public function setNom($nom)
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * Get nom
     *
     * @return string 
     */
    public function getNom()
    {
        return $this->nom;
    }
}
*****************************
entity Media.php:
*************
<?php

namespace Oilexport\OilexportBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * media
 *
 * @ORM\Table("media")
 * @ORM\Entity(repositoryClass="Oilexport\OilexportBundle\Repository\MediaRepository")
 */
class media
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="path", type="string", length=255)
     */
    private $path;

    /**
     * @var string
     *
     * @ORM\Column(name="alt", type="string", length=125)
     */
    private $alt;

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set path
     *
     * @param string $path
     * @return media
     */
    public function setPath($path)
    {
        $this->path = $path;

        return $this;
    }

    /**
     * Get path
     *
     * @return string 
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Set alt
     *
     * @param string $alt
     * @return media
     */
    public function setAlt($alt)
    {
        $this->alt = $alt;

        return $this;
    }

    /**
     * Get alt
     *
     * @return string 
     */
    public function getAlt()
    {
        return $this->alt;
    }
}

**Comment by fre5h** [comment]
@lotfikhalifa How it is related to my bundle? I would like to help, but it is not enough information.
