### ISSUE TITLE
Enum default value

### ISSUE THREAD

**Issue by tehplague** [fre5h/DoctrineEnumBundle#91]
We are using enums for `@ORM\DiscriminatorColumn` which works quite well. As MySQL enforces a default value on non-nullable enum columns it would be nice if this bundle supported specifying them. IMHO default values would make sense in a lot more use cases than only for single table inheritance. 

Any thoughts on this?

**Comment by fre5h** [comment]
Hi. Can you give an example about what you want to be added? I didn't get it.

**Comment by tehplague** [comment]
Of course.

```sql
ALTER TABLE t_order_item ADD type type ENUM('article', 'catalog', 'discount', 'gift', 'shipping_cost', 'voucher') NOT NULL DEFAULT 'article' COMMENT '(DC2Type:OrderItemType)'
```

instead of

```sql
ALTER TABLE t_order_item CHANGE type type ENUM('article', 'catalog', 'discount', 'gift', 'shipping_cost', 'voucher') NOT NULL COMMENT '(DC2Type:OrderItemType)'
```

(note the additional `DEFAULT 'article'` in the first SQL query)

**Comment by fre5h** [comment]
If you are using ENUM field as a regular field inside some entity, then you can set default value, Doctrine allows it.

```
@ORM\Column(name="position", type="BasketballPositionType", nullable=false, options={"default": "SOME_VALUE"})
```

But when you set ENUM as DiscriminatorColumn you have not these options. You can add default value manually in the generated migration (edit it).

As I understood, you ask to add some parameter into the AbstractEnumType which will be responsible for default value. Right now I not sure if it possible. But I will investigate it soon.

**Comment by tehplague** [comment]
Unfortunately, manually editing the migration is no real solution because Doctrine would revert the column definition on each subsequent `doctrine:migration:diff`.

In my opinion it boils down to a modification of the base `getSqlDeclaration()` function in the `AbstractEnumType` class. There should be some kind of error check if the specified default value really belongs to the `$choices` array and if yes the `DEFAULT` declaration can easily be appended.
At least in case of MySQL this should work. I do not know enough about PostgreSQL`s SQL dialect to tell if this is also possible with PostgreSQL or not.

**Comment by fre5h** [comment]
What to do in the case when default value in @Column is different from the default value in Enum class?
```@ORM\Column(name="position", type="BasketballPositionType", nullable=false, options={"default": "DIFFERENT_VALUE_THAN_IN_ENUM_CLASS"})```

**Comment by tehplague** [comment]
Hotfix (needed to be applied to each enum class):

```php
final class ItemType extends AbstractEnumType
{
    const FOO_VALUE    = 'foo';
    const BAR_VALUE    = 'bar';

    protected static $choices = [
        self::FOO_VALUE => 'Foo',
        self::BAR_VALUE => 'Bar'
    ];

    public function getSqlDeclaration(array $fieldDeclaration, AbstractPlatform $platform)
    {
        $originalSqlDeclaration = parent::getSqlDeclaration($fieldDeclaration, $platform);

        return sprintf(
            '%1$s DEFAULT %2$s',
            $originalSqlDeclaration,
            $platform->quoteStringLiteral(self::FOO_VALUE)
        );
    }
}
```

Replace `self::FOO_VALUE` with an actual enum value.

However it would indeed be far better to refer to `$fieldDeclaration`, fetch the default value and apply that to the SQL declaration after testing it for validity. But at least `DiscriminatorColumn` does not support `default` but only `columnDeclaration` and I want to use enums for them, too.
