### ISSUE TITLE
[Proposition] Use reflection instead of static map

### ISSUE THREAD

**Issue by Ex3v** [fre5h/DoctrineEnumBundle#92]
Hi, 

synchronizing both class consts and map in `protected static $choices` might become problematic at times, bacause you have to keep them in sync. What do you think about using reflection to handle this, similar way to what `MyClabs` does?

**Comment by fre5h** [comment]
@Ex3v You propose to remove field `$choices` from class and get all constants via reflection? What if class should have another constant which is not a choice for ENUM?

**Comment by Ex3v** [comment]
@fre5h I believe Enums by convention should only contain available choices/states as that is their purpose - to limit them to closed list. 
Personally I cannot imagine a real world example with consts in enum that are not part of it.

**Comment by fre5h** [comment]
OK, I will think about this feature for release 6.0 (major release, because removing static $choices is kind of broken compatibility)
Thanks for idea

**Comment by Ex3v** [comment]
No problem :) Thanks!

**Comment by fre5h** [comment]
@Ex3v I forgot something. Static map allows to add readable values. If only constants are left, then how to specify readable values?

```php
<?php
namespace AppBundle\DBAL\Types;

use Fresh\DoctrineEnumBundle\DBAL\Types\AbstractEnumType;

final class BasketballPositionType extends AbstractEnumType
{
    const POINT_GUARD = 'PG';
    const SHOOTING_GUARD = 'SG';
    const SMALL_FORWARD = 'SF';
    const POWER_FORWARD = 'PF';
    const CENTER = 'C';

    protected static $choices = [
        self::POINT_GUARD => 'Point Guard',
        self::SHOOTING_GUARD => 'Shooting Guard',
        self::SMALL_FORWARD => 'Small Forward',
        self::POWER_FORWARD => 'Power Forward',
        self::CENTER => 'Center'
    ];
}
```

**Comment by Ex3v** [comment]
I didn't had to deal with this case, as I always use i18n and translation keys instead of hardcoded text. Anyway popular hack here is to implement `toString` method. That's the way it is done in Java.

```java
enum TrafficLight {
  RED,
  GREEN;

  @Override
  public String toString() {
    switch(this) {
      case RED: return "abc";
      case GREEN: return "def";
      default: throw new IllegalArgumentException();
    }
  }
}
```

Of course I see your point here. Delegating those values to array might reduce code and if someone prefer to cast enums to human-friendly strings, there is nothing wrong within it. But forcing user to use it, is.

**Comment by Blackskyliner** [comment]
In Java you actually use the type/enum though. As it's a builtin feature of the language. Which in this case the enums are not. We just insert the string after referencing them (because const)

I guess if you'd need such functionality as described you WILL have to add an static array with the translations. But nonetheless it's then an application decision and not an enforced one of the enum library. Which I see to be unnecessary too, because of the opinionated thought of saving the user friendly versions within the enum-class.

**Comment by artursvonda** [comment]
To chip in a bit, I think there's a way to satisfy all needs by having a default implementation in abstract class that transforms constant name into human-friendly name that can be overwritten by subclass. Having a clean enum class with only constants would be so nice though. :)

**Comment by fre5h** [comment]
Because custom enum type extends `\Doctrine\DBAL\Types\Type` it also extends all public constants from that class. So when we use reflection to get all constants we also get all from the parent class.
To get constants only from the child enum type, we need to make a diff. Simple example

```php
$reflectionOfCustomType = new \ReflectionClass($customEnumType);
$reflectionOfBaseType = new \ReflectionClass(\Doctrine\DBAL\Types\Type::class);

$constantsOfCustomType = array_values($reflectionOfCustomType->getConstants());
$constantsOfBaseType = array_values($reflectionOfBaseType->getConstants());

$uniqueConstantsOfCurrentType = \array_diff($constantsOfCustomType, $constantsOfBaseType);
```

**Comment by fre5h** [comment]
After release on PHP 8.1 will be used native ENUM classes in my bundle
