### ISSUE TITLE
Requiring database connection in bootstrap

### ISSUE THREAD

**Issue by el-seirh** [fre5h/DoctrineEnumBundle#93]
Hi,

When using your package with my current configuration (4 properly configured postgresql connections) I get the following error:

> An exception occured in driver: could not find driver

In the exception trace I see that your Bundle is trying to load a MySql Driver, which I do not have (nor need to have) installed.

```
Exception trace:
 () at /var/data/webroot/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43
 PDO->__construct() at /var/data/webroot/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43
 Doctrine\DBAL\Driver\PDOConnection->__construct() at /var/data/webroot/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php:41
 Doctrine\DBAL\Driver\PDOMySql\Driver->connect() at /var/data/webroot/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:360
 Doctrine\DBAL\Connection->connect() at /var/data/webroot/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:429
 Doctrine\DBAL\Connection->getDatabasePlatformVersion() at /var/data/webroot/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:389
 Doctrine\DBAL\Connection->detectDatabasePlatform() at /var/data/webroot/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:328
 Doctrine\DBAL\Connection->getDatabasePlatform() at /var/data/webroot/vendor/fresh/doctrine-enum-bundle/FreshDoctrineEnumBundle.php:36
 Fresh\DoctrineEnumBundle\FreshDoctrineEnumBundle->boot() at /var/data/webroot/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:120
 Symfony\Component\HttpKernel\Kernel->boot() at /var/data/webroot/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:68
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/data/webroot/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:121
 Symfony\Component\Console\Application->run() at /var/data/webroot/bin/console:28
```

In \Fresh\DoctrineEnumBundle\FreshDoctrineEnumBundle::boot() you loop through all connections and perform the following code on them
`$databasePlatform = $connection->getDatabasePlatform();`
With my 4 pdo_postgresql connections this works fine, however it tries to do the same with a nonexisting default connection that just uses the default parameters:
```
host = "localhost"
port = null
user = "root"
password = null
driver = "pdo_mysql"
```
That is probably mainly an issue of doctrine that should not pass over undefined default connections in 
`getConnections()` but I also find it quite strange that your bundle requires one to have an open connection when one for example just wants to perform a `cache:clear --no-warmup` on the symfony console.

The quickfix in my project is to just actively set a connection named "default" with the params of one of the other connections (since, nope, setting a `doctrine.dbal.default_connection:` won't work either).

So I think there's really two issues here:
a) Your bundle shouldn't require an active db-connection in boot() at all
b) The getConnections() should return only "valid" in the sense of "complete" or "defined" connections. If I didn't specify a default connection that's because I don't want any. 
Probably this is rather an issue to report to the Doctrine/DBAL team. But maybe there's also a way for your bundle to skip invalid connections?

Thanks for your nice bundle by the way ;).

**Comment by fre5h** [comment]
You have missed one parameter in config of Doctrine

```
doctrine:
    dbal:
        driver:         "%database_driver%"
        host:           "%database_host%"
        port:           "%database_port%"
        dbname:         "%database_name%"
        user:           "%database_user%"
        password:       "%database_password%"
        server_version: "%database_server_version%"
```

`database_server_version: 5.6`
5.6, 5.7 or what version you are using.

It is an old issue of Doctrine, that you have to specify server version manually.

Try this fix

**Comment by el-seirh** [comment]
Thanks for the hint. I've actually tried the server_version param before, but only in my actually defined db connections. If I put both the _server_version_ AND the _driver_ there, you are right, there will be no db connection opened by doctrine to get these values.

But that technically still does not solve the main issue of the faulty "default" connection. In order to get around that problem, I do have to define it and set at least the driver and server_version param to avoid it getting opened. So my config now looks like this:

```
doctrine:
    dbal:
        connections:
            default:
                driver:   pdo_pgsql
                server_version: "%database_server_version%"
            my_custom_connection:
                driver:   pdo_pgsql
                host:     "%custom_database_host%"
                port:     "%custom_database_port%"
                dbname:   "%custom_database_name%"
                user:     "%custom_database_user%"
                password: "%custom_database_password%"
                charset:  UTF8
            my_second_custom_connection:
                [...]
```

I presume this problem only occurs in a multiconnection setup. In your example where you only have one connection doctrine probably takes that one as default right away so you'll never run into the problem with the wrong driver (and even less if you use mysql anyway).

I have to say it still feels weird to have to hardcode your server version in the config.

So I still stick to my point that doctrine a) shouldn't provide you with a default connection that was not defined and b) should at least accept the `doctrine.dbal.default_connection:` parameter to overwrite the default connection instead of just looking for a connection named "default".

**Comment by el-seirh** [comment]
I have a simple but radical proposition for you that would fix this problem for future users.

          ```
  try {
                /** @var AbstractPlatform $databasePlatform */
                $databasePlatform = $connection->getDatabasePlatform();
            } catch (\Doctrine\DBAL\Exception\DriverException $e) {
                continue;
            }
```

Yeah that's right: if that driver issue comes up, just ignore it. I know this seems dirty at first, but consider the following points:
- Why inject your enum functionality into a connection that is improperly configured at all? That doesn't make sense right?
- Why breaking a systems basic workflow (and I mean _everything_ that uses the symfony console) for a connection that wasn't even specified?
- Why breaking a systems basic workflow for a bundle that just handles some enum type support? 
My last point is a little weak, but you know ... I'm really considering if hardcoding the server version equals what I gain by using the bundle. And that's a pitty I think. Cause your bundle is well made.

Probably there is some reasoning behind Doctrine providing this default connection like this, but I don't really see it. I might take the effort to report open issue with them.
But I still think your bundle needs to address this issue in some way in order to avoid users like me report this issue over and over again.

Cheers. Of course feel free to reject my proposal. No hard feelings.

PS: You might wanna change that Exception to a more general Type, e.g. `\Doctrine\DBAL\Exception` for it to cover more cases.

**Comment by samdark** [comment]
Encountered the same issue with a single connection defined. I have `server_version` there:

```yaml
doctrine:
    dbal:
        driver: 'pdo_pgsql'
        url: '%env(DATABASE_URL)%'
        server_version: '9.4'
```

When trying to run console it fails to connect to MySQL I'm not having at all defined in the project.

**Comment by samdark** [comment]
At the bootstrap stage Doctrine seems to have default connection only. At least in Symfony 4.

**Comment by fre5h** [comment]
\Fresh\DoctrineEnumBundle\FreshDoctrineEnumBundle was rewritten, `boot` method was replaced with complier pass, should work now
