### ISSUE TITLE
Label translation

### ISSUE THREAD

**Issue by padalec** [fre5h/DoctrineEnumBundle#95]
Hi
how can I use translator for translate labels? 
Regards

**Comment by fre5h** [comment]
@padalec Hi, where exactly do you want to use translator: twig templates or somewhere else?

**Comment by padalec** [comment]
Hi 
I use method  getChoices() in my form type class and there I need to translate some labels
Regards

**Comment by fre5h** [comment]
ChoiceType provides translation out of box. Just write translations into your messages.yml (etc.) for your choices, it should work.

**Comment by padalec** [comment]
great, thanks! It's works perfectly!
