### ISSUE TITLE
Symfony 3.3 compatibility ....

### ISSUE THREAD

**Issue by reypm** [fre5h/DoctrineEnumBundle#98]
@fre5h will you upgrade this bundle to support Symfony 3.3 soon? I am trying to upgrade my project to Symfony 3.3 but I can't because this bundle:

`- fresh/doctrine-enum-bundle v5.0.1 requires symfony/validator ~3.2 -> satisfiable by symfony/symfony[v3.2.9], symfony/validator[v3.2.0, v3.2.1, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7, v3.2.8, v3.2.9, v3.3.0, v3.3.1, v3.3.2].
`

**Comment by fre5h** [comment]
Yes, I will fix it soon

**Comment by fre5h** [comment]
@reypm I tried to investigate this issue, but couldn't reproduce. I created a new symfony project on version 3.3.2 via symfony installer. then added my bundle as dependency `"fresh/doctrine-enum-bundle":"~5.0"` and ran `composer update`, and got no error.

Can you reproduce it again or show me your composer.json?

**Comment by reypm** [comment]
@fre5h here is my composer.json:

```
{
    "type": "project",
    "autoload": {
        "psr-4": { "": "src/" },
        "classmap": [ "app/AppKernel.php", "app/AppCache.php" ]
    },
    "autoload-dev": {
        "psr-4": {
          "mmi\\": "../library/mmi/",
          "share\\": "library/",
          "Tests\\": "tests/"
        },
        "classmap": ["../application/"]
    },
    "require": {
        "symfony/symfony": "3.2.*",
        "doctrine/orm": "^2.5",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-cache-bundle": "^1.2",
        "symfony/swiftmailer-bundle": "^2.3.10",
        "symfony/monolog-bundle": "^3.0.2",
        "symfony/polyfill-apcu": "^1.0",
        "sensio/distribution-bundle": "^5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "^2.0",
        "twig/twig": "^1.0||^2.0",
        "zendframework/zendframework1": "^1.12",
        "sensiolabs/ansi-to-html": "^1.1",
        "stof/doctrine-extensions-bundle": "^1.2",
        "javiereguiluz/easyadmin-bundle": "^1.16",
        "fresh/doctrine-enum-bundle": "^5.0",
        "alcaeus/mongo-php-adapter": "^1.0",
        "doctrine/mongodb-odm": "^1.1",
        "doctrine/mongodb-odm-bundle": "^3.0",
        "willdurand/js-translation-bundle": "^2.6",
        "knplabs/knp-snappy-bundle": "~1.4",
        "guzzlehttp/guzzle": "~6.0",
        "easycorp/easy-log-handler": "^1.0",
        "lexik/translation-bundle": "~4.0",
        "php-http/httplug-bundle": "^1.4",
        "php-http/guzzle6-adapter": "^1.1",
        "php-http/curl-client": "^1.7",
        "liuggio/excelbundle": "^2.1",
        "egeloen/ckeditor-bundle": "^5.0",
        "friendsofsymfony/jsrouting-bundle": "^1.6",
        "twig/extensions": "^1.5"
    },
    "require-dev": {
        "sensio/generator-bundle": "^3.0",
        "symfony/phpunit-bridge": "^3.0",
        "phpunit/phpunit": "^6.1"
    },
    "scripts": {
        "symfony-scripts": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ],
        "post-install-cmd": [
            "@symfony-scripts",
            "/bin/cp -rf /composer_files/Session.php /var/www/html/oneview_symfony/vendor/zendframework/zendframework1/library/Zend/Session.php"
        ],
        "post-update-cmd": [
            "@symfony-scripts",
            "/bin/cp -rf /composer_files/Session.php /var/www/html/oneview_symfony/vendor/zendframework/zendframework1/library/Zend/Session.php"
        ]
    },
    "config": {
        "platform": {
            "php": "7"
        }
    },
    "extra": {
        "symfony-app-dir": "app",
        "symfony-bin-dir": "bin",
        "symfony-var-dir": "var",
        "symfony-web-dir": "web",
        "symfony-tests-dir": "tests",
        "symfony-assets-install": "symlink",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        },
        "branch-alias": {
            "dev-master": "3.2-dev"
        }
    }
}

```

**Comment by fre5h** [comment]
Strange, but with your composer.json I didn't have the issue you posted. Try to delete your vendors and run `composer update` again

**Comment by reypm** [comment]
Ohhh sorry, the problem comes when you try to upgrade Symfony from `3.2.*` to `3.3.*`. Having this the right `composer.json` should be:

    "require": {
        "symfony/symfony": "3.0.*",
        "doctrine/orm": "^2.5",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-cache-bundle": "^1.2",
        "symfony/swiftmailer-bundle": "^2.3.10",
        "symfony/monolog-bundle": "^3.0.2",
        "symfony/polyfill-apcu": "^1.0",
        "sensio/distribution-bundle": "^5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "^2.0",
        "twig/twig": "^1.0||^2.0",
        "zendframework/zendframework1": "^1.12",
        "sensiolabs/ansi-to-html": "^1.1",
        "stof/doctrine-extensions-bundle": "^1.2",
        "javiereguiluz/easyadmin-bundle": "^1.16",
        "fresh/doctrine-enum-bundle": "^5.0",
        "alcaeus/mongo-php-adapter": "^1.0",
        "doctrine/mongodb-odm": "^1.1",
        "doctrine/mongodb-odm-bundle": "^3.0",
        "willdurand/js-translation-bundle": "^2.6",
        "knplabs/knp-snappy-bundle": "~1.4",
        "guzzlehttp/guzzle": "~6.0",
        "easycorp/easy-log-handler": "^1.0",
        "lexik/translation-bundle": "~4.0",
        "php-http/httplug-bundle": "^1.4",
        "php-http/guzzle6-adapter": "^1.1",
        "php-http/curl-client": "^1.7",
        "liuggio/excelbundle": "^2.1",
        "egeloen/ckeditor-bundle": "^5.0",
        "friendsofsymfony/jsrouting-bundle": "^1.6",
        "twig/extensions": "^1.5"
    },

**Comment by fre5h** [comment]
@reypm But in this composer.json I see next `"symfony/symfony": "3.0.*",` Why 3.0? Check your code, maybe there you have same typo.

**Comment by reypm** [comment]
@fre5h unless I am wrong this is what Symfony.com site says [here](https://symfony.com/doc/current/setup/upgrade_major.html#update-to-the-new-major-version-via-composer) for upgrade to latest version, I am wrong?

**Comment by reypm** [comment]
@fre5h well, not sure but that seems to be wrong, I have updated the `composer.json` file for Symfony to this: `"symfony/symfony": "3.3.*",` and the update works properly. I will close this. Thanks for your time.

**Comment by fre5h** [comment]
@reypm 
There sad a **MAJOR** version. Check this http://semver.org/#summary
1.0, 2.0, 3.0, 4.0 - are Major versions.
3.1, 3.2, 3.3 - are Minor versions.
3.3.0, 3.3.1, 3.3.2 - are patch versions.

`3.0.*` - is a lock for all patches for minor changes of Symfony 3.0

If you want to use Symfony 3.3 then update your version to `3.3.*` or `~3.3`
